// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSkDDN2_c4Cwb_Uv5ja9tKVcGGmoOhRl8',
    appId: '1:870148798408:web:ad19ea6a25da1a5238f2fd',
    messagingSenderId: '870148798408',
    projectId: 'youwouldn-tstealalandmower',
    authDomain: 'youwouldn-tstealalandmower.firebaseapp.com',
    storageBucket: 'youwouldn-tstealalandmower.firebasestorage.app',
    measurementId: 'G-3PKHBLEE6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOHh5lbBPP2jguOu3ujgkQwCCH9Sb-Q5E',
    appId: '1:870148798408:android:8b92ab593ba015ea38f2fd',
    messagingSenderId: '870148798408',
    projectId: 'youwouldn-tstealalandmower',
    storageBucket: 'youwouldn-tstealalandmower.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD181NDo2Zn2ijHeDOoZ0JttWKoNXv_dCA',
    appId: '1:870148798408:ios:56c93a5c4c32364338f2fd',
    messagingSenderId: '870148798408',
    projectId: 'youwouldn-tstealalandmower',
    storageBucket: 'youwouldn-tstealalandmower.firebasestorage.app',
    iosBundleId: 'com.example.youWouldntStealALawnmower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD181NDo2Zn2ijHeDOoZ0JttWKoNXv_dCA',
    appId: '1:870148798408:ios:56c93a5c4c32364338f2fd',
    messagingSenderId: '870148798408',
    projectId: 'youwouldn-tstealalandmower',
    storageBucket: 'youwouldn-tstealalandmower.firebasestorage.app',
    iosBundleId: 'com.example.youWouldntStealALawnmower',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSkDDN2_c4Cwb_Uv5ja9tKVcGGmoOhRl8',
    appId: '1:870148798408:web:7eb421d9d080d6b938f2fd',
    messagingSenderId: '870148798408',
    projectId: 'youwouldn-tstealalandmower',
    authDomain: 'youwouldn-tstealalandmower.firebaseapp.com',
    storageBucket: 'youwouldn-tstealalandmower.firebasestorage.app',
    measurementId: 'G-GXHEZHCX5P',
  );
}
